---
  - hosts: concourseCi
    roles:
  #=================OK============================================================
      - { role: Prerequisites, tags: [ 'setup' ] }
      - { role: InstallAndConfigurePostgreSQL, tags: [ 'setup' ] }
      - { role: DownloadAndInstallConcourseCI, tags: [ 'setup' ] }
      - { role: GenerateAndSetupRSAKeys, tags: [ 'setup' ] }
      - { role: ConfigureEnvironmentAndSystemdService, tags: [ 'setup' ] }
      - { role: SettingUpNginxReverseProxy, tags: [ 'setup' ] }
